# Generated by Django 3.2.12 on 2024-01-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.CharField(max_length=200)),
                ('isp', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='IPGeolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('hostname', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country_code', models.CharField(max_length=200)),
                ('country_name', models.CharField(max_length=200)),
                ('region_code', models.CharField(max_length=200)),
                ('region_name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('zip', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_proxy', models.BooleanField()),
                ('proxy_type', models.CharField(blank=True, max_length=200, null=True)),
                ('is_crawler', models.BooleanField()),
                ('crawler_name', models.CharField(blank=True, max_length=200, null=True)),
                ('crawler_type', models.CharField(blank=True, max_length=200, null=True)),
                ('is_tor', models.BooleanField()),
                ('threat_level', models.CharField(max_length=200)),
                ('threat_types', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.CharField(max_length=200)),
                ('gmt_offset', models.IntegerField()),
                ('code', models.CharField(max_length=200)),
                ('is_daylight_saving', models.BooleanField()),
            ],
        ),
    ]
